### ISSUE TITLE
options not working with Angular 11.1.1

### ISSUE THREAD

**Issue by manojkumarbehera** [skynet2/ngx-google-places-autocomplete#92]
options have error

` <input ngx-google-places-autocomplete [options]='options'  #placesRef="ngx-places" (onAddressChange)="handleAddressChange($event)"/>`
  
```
options = {
    componentRestrictions: {
      country: ['IN'],
    },
  };
```
And the error is :
Error: src/app/app.component.html:6:42 - error TS2739: Type '{ componentRestrictions: { cong the following properties from type 'Options': bounds, types, fields, strictBounds, orig
